
export interface ReplacementProduct {
  productCode: string;
  modelNo: string;
  description: string;
  currentStock: string;
  replacement: string;
  replacementAvailable: string;
}

export const replacementList: ReplacementProduct[] = [
  { productCode: "3151", modelNo: "VBV-L407", description: "Select Camera Ext Cable - 7m", currentStock: "893", replacement: "5517", replacementAvailable: "YES" },
  { productCode: "3152", modelNo: "VBV-L406", description: "Select Camera Ext Cable - 6m", currentStock: "957", replacement: "5518", replacementAvailable: "YES" },
  { productCode: "3840", modelNo: "VBV-770FM-CA", description: "Monitor Spare Part, Power & Video Cable, VBV-770FM", currentStock: "10", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3869", modelNo: "VSP-57A", description: "Coiled Cables Kit, 7-Pin B/head Skt for Truck", currentStock: "215", replacement: "No replacement", replacementAvailable: "TBC" },
  { productCode: "3870", modelNo: "VSP-57B", description: "Coiled Cables Part, 7-Pin B/head Skt for Trailer", currentStock: "321", replacement: "No replacement", replacementAvailable: "TBC" },
  { productCode: "4001", modelNo: "VBV-L505", description: "Select Camera Cable, 5-pin for VBV-710C Camera 5m", currentStock: "341", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4019", modelNo: "VBV-770D-104", description: "CMS Select, 7\" LCD, T/S Cameras (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4246", modelNo: "AC-042", description: "CMS Adpt Cable, Select Camera to 7-Way AMP", currentStock: "1381", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "4279", modelNo: "AC-044", description: "CMS Adpt Cable, Select Camera to Molex M12", currentStock: "749", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "4287", modelNo: "VBV-750M", description: "Select Monitor, 5\" LCD, 3 Inputs, Audio", currentStock: "0", replacement: "5611A", replacementAvailable: "YES" },
  { productCode: "4288", modelNo: "VBV-770M", description: "Select Monitor, 7\" LCD, 3 Inputs, Audio", currentStock: "1", replacement: "5611A", replacementAvailable: "YES" },
  { productCode: "4349", modelNo: "VBV-L410(C)", description: "Select Camera Ext Cable In Conduit - 10m", currentStock: "691", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "4350", modelNo: "VBV-L415(C)", description: "Select Camera Ext Cable In Conduit - 15m", currentStock: "1186", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "4397", modelNo: "BE-870L-090", description: "CMS Elite, 7 In LCD, Sgl IP69K Cam - Lrg Rgd (PAL)", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4474", modelNo: "VBV-7104FM", description: "Select Monitor, 10.4\" LCD, 4 Inputs, Audio", currentStock: "0", replacement: "6057A", replacementAvailable: "YES" },
  { productCode: "4604", modelNo: "VBV-300C", description: "Select Camera, F/mount Eyeball (Mirror) (PAL)", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4611", modelNo: "VBV-301C", description: "Select Camera, F/mount Eyeball (Mirror) (NTSC)", currentStock: "4", replacement: "7144", replacementAvailable: "YES" },
  { productCode: "4613", modelNo: "VBV-320C", description: "Select Camera, F/mount Eyeball (Normal) (PAL)", currentStock: "1", replacement: "7145", replacementAvailable: "YES" },
  { productCode: "4615", modelNo: "VBV-321C", description: "SE Cam, Compact F/M Eyeball Cam (Normal Im) (NTSC)", currentStock: "0", replacement: "7146", replacementAvailable: "YES" },
  { productCode: "4673", modelNo: "VBV-700C(M12)", description: "Select Camera, Audio + M12 Connector (COBO)", currentStock: "32", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4692", modelNo: "VBV-770-000", description: "CMS Select, 7\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "0", replacement: "AHD version: 8144", replacementAvailable: "YES" },
  { productCode: "4705", modelNo: "VBV-750-000", description: "CMS Select, 5\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4707", modelNo: "VBV-750-010N", description: "VBV-750-010N", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4710", modelNo: "VBV-750M-S", description: "Select Monitor, 5\" LCD, 3 Inputs, Audio", currentStock: "27", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4746", modelNo: "VSP-57ABS-C", description: "Coil Cab Kit Part, 7-Pin B/head Socket for Truck", currentStock: "21", replacement: "No replacement", replacementAvailable: "TBC" },
  { productCode: "4747", modelNo: "VSP-57ABS-T", description: "Coil Cab Kit Part, 7-Pin B/head Socket for Trailer", currentStock: "110", replacement: "No replacement", replacementAvailable: "TBC" },
  { productCode: "4767", modelNo: "VBV-770-001", description: "CMS SE, 7\" LCD, Sin Cam - Artic Trucks (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4772", modelNo: "VBV-770-101", description: "CMS SE, 7\" LCD, S/S Cam - Artic Trucks (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4776", modelNo: "VBV-750-300", description: "CMS SE, 5\" LCD, F/M Cam - L Rig (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4791", modelNo: "VBV-750-010", description: "CMS Select, 5\" LCD, Single Camera - S Rig (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4843", modelNo: "VBV-770-001DW", description: "7\" LCD, Single Cam & Wireless Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4910", modelNo: "DMC-1025", description: "Elite Camera, Mini Camera (Internal Use) (PAL)", currentStock: "2", replacement: "5719 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "4977", modelNo: "VBV-L403", description: "Select Camera Ext Cable - 3m", currentStock: "262", replacement: "5521", replacementAvailable: "YES" },
  { productCode: "4981", modelNo: "MDR-500 DEMO", description: "MDR-500 Demo Kit", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4982", modelNo: "VBV-770FM", description: "Select Monitor, 7\" LCD, 4 Inputs, Audio", currentStock: "3", replacement: "7204", replacementAvailable: "YES" },
  { productCode: "5028", modelNo: "AC-067", description: "CMS Adpt Cable, Orlaco Camera to Select Monitor", currentStock: "678", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "5075", modelNo: "VBV-700C-002", description: "Select Camera, Audio + Cable + Cable Adapter (DAF)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5080", modelNo: "VBV-L405(KV)", description: "Select Cam Ext Cable - 5m with 1m Kevlar Cable", currentStock: "209", replacement: "6193", replacementAvailable: "YES" },
  { productCode: "5082", modelNo: "VBV-750M(404)", description: "Select Monitor, 5\" LCD, 3 Inputs, Audio", currentStock: "53", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5088", modelNo: "VBV-770M(DTM)", description: "Select Monitor, 7\" LCD, 3 Inputs, Audio - 3 Inputs", currentStock: "22", replacement: "7705", replacementAvailable: "YES" },
  { productCode: "5100", modelNo: "BE-823C", description: "Elite Camera, Mini Camera (Normal Image) (NTSC)", currentStock: "4", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5163", modelNo: "DMC-1021", description: "Elite Camera, Mini Camera (Internal Use) (NTSC)", currentStock: "3", replacement: "5721 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "5164", modelNo: "MD-51", description: "Elite Camera, Mini Dome Camera (NTSC)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5178", modelNo: "FORS Gold", description: "CMS SE, 7\" LCD, Quad Cams & MDR (PAL) (MANN)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5179", modelNo: "FORS Silver", description: "CMS Select, 7\" LCD, Quad Cameras, Sidescan, Backch", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5211", modelNo: "VBV-300C", description: "Select Camera, F/mount Eyeball (Mirror) (PAL)", currentStock: "12", replacement: "5211A", replacementAvailable: "YES" },
  { productCode: "5213", modelNo: "VBV-301C", description: "Select Camera, F/mount Eyeball (Mirror) (NTSC)", currentStock: "90", replacement: "7144", replacementAvailable: "YES" },
  { productCode: "5215", modelNo: "VBV-320C", description: "Select Camera, F/mount Eyeball (Normal) (PAL)", currentStock: "18", replacement: "7145", replacementAvailable: "YES" },
  { productCode: "5217", modelNo: "VBV-321C", description: "SE Cam, Comp F/M Eyeball Cam (Norm Img) (NTSC) CCD", currentStock: "3", replacement: "7146", replacementAvailable: "YES" },
  { productCode: "5234", modelNo: "AC-068", description: "CMS Adpt Cable, Select Camera to MAN Harman MFD", currentStock: "2107", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "5251", modelNo: "VBV-770FM(2DC)", description: "Select Monitor, 7\" LCD, 2 x Deutsch on Cable Adp (", currentStock: "5", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5277", modelNo: "BE-900C", description: "Elite Camera, Heated & Audio -Distortion Con(PAL)", currentStock: "4", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5278", modelNo: "BE-901C", description: "Elite Camera, Heated & Audio -Distortion Con(NTSC)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5279", modelNo: "BE-990C", description: "Elite Camera, Heated - Distortion Control (PAL)", currentStock: "135", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5280", modelNo: "BE-991C", description: "Elite Camera, Heated - Distortion Control (NTSC)", currentStock: "6", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5300", modelNo: "VBV-L405(4.8KV)", description: "Select Cam Ext Cable - 5m with 4.8m Kevlar Cable", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5318", modelNo: "AC-069", description: "CMS Adpt Cable, Select Cam to Scania/MAN Harman", currentStock: "2009", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "5340", modelNo: "CMS SE, Rigid Unit-FORS Silver/CLOCS Kit (SCANIA)", description: "CMS SE, Rigid Unit-FORS Silver/CLOCS Kit (SCANIA)", currentStock: "4", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5378", modelNo: "SE-7104F-100", description: "Backeye®360 BN360 Kit, 10.4\" Monitor - Lrg Rigids", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5379", modelNo: "SE-770-100", description: "Backeye®360 BN360 Kit, 7\" Monitor - Large Rigids", currentStock: "2", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5381", modelNo: "SE-770-111", description: "Backeye®360 BN-360 Kit, 7\" Monitor - L Rig", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5382", modelNo: "SE-770-110", description: "Backeye®360 BN-360 Kit, 7\" Monitor - L Rig", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5406", modelNo: "BRI-870-MD50", description: "CMS Elite, 7 Inch LCD, 2 x MD50 Camera (Sesaly)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5412", modelNo: "VBV-243-300", description: "CMS Select, 4.3 Inch LCD Mirror Monitor, 1 Input", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5413", modelNo: "VBV-243-000", description: "CMS Kit for Tevo", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5426", modelNo: "BE-891C", description: "Elite Camera, Waterproof to IP69K -No Audio (NTSC)", currentStock: "0", replacement: "1623E", replacementAvailable: "YES" },
  { productCode: "5430", modelNo: "AC-070", description: "Adaptor Cable", currentStock: "870", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "5454", modelNo: "VBV-3000C", description: "Select Camera, F/mount Eyeball (Mirror) 720p 25fps", currentStock: "145", replacement: "7143", replacementAvailable: "YES" },
  { productCode: "5455", modelNo: "VBV-3001C", description: "Select Camera, F/mount Eyeball (Mirror) 720p 30fps", currentStock: "1167", replacement: "7144", replacementAvailable: "YES" },
  { productCode: "5456", modelNo: "VBV-3020C", description: "Select Camera, F/mount Eyeball (Normal) 720p 25fps", currentStock: "19", replacement: "7145", replacementAvailable: "YES" },
  { productCode: "5457", modelNo: "VBV-3021C", description: "Select Camera, F/mount Eyeball (Normal) 720p 30fps", currentStock: "234", replacement: "7146", replacementAvailable: "YES" },
  { productCode: "5464", modelNo: "VBV-7000C", description: "Select Camera, Audio, HD 720p 25fps", currentStock: "4", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "5465", modelNo: "VBV-7001C", description: "Select Camera, Audio, HD 720p 30fps", currentStock: "393", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "5468", modelNo: "VBV-7090C", description: "Select Camera, IP69K - No Audio, HD 720p 25fps", currentStock: "294", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "5469", modelNo: "VBV-7091C", description: "Select Camera, IP69K - No Audio, HD 720p 30fps", currentStock: "90", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "5470", modelNo: "VBV-7190C", description: "Select Camera, IP69K - No Audio, HD 1080p 25fps", currentStock: "1", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "5471", modelNo: "VBV-7191C", description: "Select Camera, IP69K - No Audio, HD 1080p 30fps", currentStock: "1", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "5481", modelNo: "VBV-750DM(DTM)", description: "SE Mon, 5\" LCD, 3 In, Audio, 3X4-Pin In w/DTM Con", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5493", modelNo: "VBV-790C(CO)", description: "Select Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "0", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "5528", modelNo: "AC-069-90", description: "CMS A/C, SE Cam to Scania/MAN unit w/o Cam prep", currentStock: "2845", replacement: "No current replacement, but HD cables can be used if needed", replacementAvailable: "TBC" },
  { productCode: "5544", modelNo: "TA-770-4S", description: "Turnassist™ 4 Sensor Sidescan / View Kit", currentStock: "43", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5545", modelNo: "TA-770-2S", description: "Turnassist™ 2 Sensor Sidescan / View Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5592", modelNo: "SE-770-101", description: "Backeye®360 BN360 Kit, 7\" Monitor, 4 x 10m cables", currentStock: "2", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5630", modelNo: "VBV-L415 (KV-1) Blue kevlar cable", description: "Select Camera Blue Kevlar Extension Cable - 15m", currentStock: "5", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5683", modelNo: "MD-50 (SW)", description: "Select Camera, Mini Dome Camera, Super Wide (PAL)", currentStock: "615", replacement: "5688", replacementAvailable: "YES" },
  { productCode: "5686", modelNo: "MD-51 (SW)", description: "Select Camera, Mini Dome Camera, Super Wide (NTSC)", currentStock: "13", replacement: "5690", replacementAvailable: "YES" },
  { productCode: "5692", modelNo: "MD-50(W)", description: "Select Camera, Mini Dome Camera, Wide Angle (PAL)", currentStock: "723", replacement: "5696", replacementAvailable: "YES" },
  { productCode: "5694", modelNo: "MD-51 (W)", description: "Select Camera, Mini Dome Camera, Wide Angle (NTSC)", currentStock: "64", replacement: "5698", replacementAvailable: "YES" },
  { productCode: "5715", modelNo: "DMC-1021", description: "Select Camera, Mini Camera (Internal Use) (NTSC)", currentStock: "96", replacement: "5721 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "5717", modelNo: "DMC-1025", description: "Select Camera, Mini Camera (Internal Use) (PAL)", currentStock: "96", replacement: "5719 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "5735", modelNo: "MD-50", description: "Select Camera, Mini Dome Camera (PAL)", currentStock: "590", replacement: "5737", replacementAvailable: "YES" },
  { productCode: "5736", modelNo: "MD-51", description: "Select Camera, Mini Dome Camera (NTSC)", currentStock: "853", replacement: "5738", replacementAvailable: "YES" },
  { productCode: "5783", modelNo: "VBV-300C (CO-DIS)", description: "Select Camera, Kit with Conduit and Disassembled", currentStock: "457", replacement: "TBC", replacementAvailable: "TBC" },
  { productCode: "5923", modelNo: "BIFFA 4 CAM MDR KIT", description: "Biffa Normal Spec 4 Camera MDR Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5934", modelNo: "PREVOST 900273 KIT", description: "PREVOST Backeye 360 Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5949", modelNo: "VBV-770M(DC)", description: "VBV-770M with DTM Connector added to CA", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6068", modelNo: "DAF-DVS-01(UK Version)", description: "DAF Kit for DVS - UK Version", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6076", modelNo: "DVS-SS-01", description: "DVS Compliant Kit - Rigid Vehicles", currentStock: "7", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6077", modelNo: "FORS-SS-01", description: "FORS Compliant Cam & Side Detection Sys for rigids", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6078", modelNo: "DVS-CS-01", description: "DVS Compliant Kit - Articulated Vehicles", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6082", modelNo: "VBV-L4025(CO)", description: "SE Cam Extension Cable - 2.5m + Conduit (No bag)", currentStock: "956", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6089", modelNo: "DAF-DVS ARTIC(UK Version)", description: "DAF DVS Artic Kit - UK Version", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6090", modelNo: "VBV-L4025(NPK)", description: "Select Camera Extension Cable - 2.5m (no bag)", currentStock: "100", replacement: "TBC", replacementAvailable: "TBC" },
  { productCode: "6091", modelNo: "VBV-L403(NPK)", description: "Select Camera Extension Cable - 3m (no bag)", currentStock: "248", replacement: "TBC", replacementAvailable: "TBC" },
  { productCode: "6093", modelNo: "VBV-L405(NPK)", description: "Select Camera Extension Cable - 5m (no bag)", currentStock: "380", replacement: "TBC", replacementAvailable: "TBC" },
  { productCode: "6094", modelNo: "VBV-L406(NPK)", description: "Select Camera Extension Cable - 6m (no bag)", currentStock: "350", replacement: "TBC", replacementAvailable: "TBC" },
  { productCode: "6111", modelNo: "VBV-770H-7000", description: "CMS Select HD, 7\" LCD, Single Cam (720p, 25ftp)", currentStock: "98", replacement: "7670", replacementAvailable: "YES" },
  { productCode: "6112", modelNo: "VBV-770H-3000", description: "CMS Select HD, 7\" LCD, Flush Cam (720p, 25ftp)", currentStock: "7", replacement: "7680", replacementAvailable: "YES" },
  { productCode: "6113", modelNo: "VBV-770H-3100", description: "CMS Select HD, 7\" LCD, Flush Cam (720p, 25ftp)", currentStock: "3", replacement: "7681", replacementAvailable: "YES" },
  { productCode: "6119", modelNo: "VBV-770M(DIN)", description: "VBV-770M w/ DIN 9680 Con added to Cable Adaptor", currentStock: "120", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6121", modelNo: "TA-770HM-2S-FLEX", description: "KSS Toter-Winkel-Warnsystem Stepcan 2S-PLUS", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6122", modelNo: "TA-770HM-4S-FLEX", description: "KSS Toter-Winkel-Warnsystem Sidescan 4S Flex", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6123", modelNo: "VBV-770H-7001", description: "CMS SE, Single AHD Cam Mon Sys for rigids", currentStock: "60", replacement: "New kit will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "6138", modelNo: "GIST KIT A", description: "DVS Rigid 2TB 4G Gist", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6139", modelNo: "GIST KIT B", description: "DVS Tractor 2TB 4G Gist", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6196", modelNo: "SCANIA-DVS-TRACTOR", description: "DVS Scania Tractor Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6197", modelNo: "SCANIA-DVS-RIGID", description: "DVS Scania Rigid Vehicles", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6198", modelNo: "SCANIA-DVS-TRACTOR-OEM", description: "DVS Scania Tractor OEM", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6208", modelNo: "K3054420 0", description: "Camera Only Kit for Kuhn", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6209", modelNo: "K3054430 0", description: "Camera Monitor Kit for Kuhn", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6210", modelNo: "83234107", description: "FM Camera Monitor Kit for Kuhn", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6237", modelNo: "DVS-PROMO 1 AHD FLEX", description: "DVS Promo 1 AHD Sidescan Flex Kit", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6238", modelNo: "DVS-PROMO 2 AHD STD", description: "DVS Promo 2 AHD Standard Kit", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6239", modelNo: "DVS-PROMO 3 AHD CORNER", description: "DVS Promo 3 AHD Corner Kit", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6315", modelNo: "VBV-790C(OG)", description: "Select Camera, Waterproof to IP69K - No Audio (PAL", currentStock: "2926", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "6319", modelNo: "83234103", description: "Camera Kit for Kuhn", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6320", modelNo: "DVS-CS-02", description: "DVS Cornerscan Alarm Kit for TRP", currentStock: "3", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6321", modelNo: "DVS-SS-02", description: "DVS Side Turn Alarm Kit for TRP", currentStock: "3", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6377", modelNo: "DVS-CS-04", description: "DVS Cornerscan LHD Kit w/o Mon for Artic Vehicles", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6378", modelNo: "DVS-SS-04", description: "DVS Side Turn LHD Kit w/o Mon for rigids", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6397", modelNo: "SCANIA 4 CAM RIGID OEM", description: "Scania 4-Camera Rigid Vehicles OEM", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6398", modelNo: "SCANIA 4 CAM RIGID ALL", description: "Scania 4-Camera Rigid Vehicles All", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6400", modelNo: "SCANIA 3 CAM TRACTOR ALL", description: "Scania 3` -Camera Tractor - All", currentStock: "0", replacement: "No replacement - can be replaced if needed", replacementAvailable: "NO" },
  { productCode: "6533", modelNo: "VBV-790C(NSCO)", description: "Select Camera, Waterproof to IP69K - No Audio (PAL", currentStock: "0", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "6543", modelNo: "DVS-770-4200-82A", description: "DVS LHD Kit (Rigid) Alternative", currentStock: "9", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6544", modelNo: "DVS-770-3100-82A", description: "DVS LHD Kit (Artic) Alternative", currentStock: "0", replacement: "No replacement - Other DVS kits available", replacementAvailable: "NO" },
  { productCode: "6545", modelNo: "DVS-770-4200W-TI", description: "DVS LHD Kit BBS-TI (Rigid) Alternative", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "6546", modelNo: "DVS-770-3100-TI", description: "DVS LHD Kit BBS-TI (Artic) Alternative", currentStock: "10", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "7217", modelNo: "VBV-770-910", description: "VBV-791C kit with VBV-770M and 10M cable", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "7250", modelNo: "FX-10.4-01 AHD", description: "3 Camera System with 10.4\" monitor", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "7251", modelNo: "FX-7-01 AHD", description: "FX Sense & Vision AHD Reversing Safety Kit, 7\" Mon", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "015.335-00", modelNo: "VBV-770M (HELLA)", description: "Select Monitor, 7 Inch LCD, 3 Inputs, Audio", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "1379D", modelNo: "VBV-700C", description: "Select Camera, Audio (PAL)", currentStock: "139", replacement: "1379E", replacementAvailable: "YES" },
  { productCode: "2199C", modelNo: "VBV-485C", description: "Select Camera, Cylinder Camera (PAL)", currentStock: "889", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "2575B", modelNo: "VBV-701C", description: "Select Camera, Audio (NTSC)", currentStock: "0", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "2575C", modelNo: "VBV-701C", description: "Select Camera, Audio (NTSC)", currentStock: "5", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "2575D", modelNo: "VBV-701C", description: "Select Camera, Audio (NTSC)", currentStock: "124", replacement: "5467A", replacementAvailable: "YES" },
  { productCode: "2724C", modelNo: "VBV-790C", description: "Select Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "4", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "2724D", modelNo: "VBV-790C", description: "Select Camera, Waterproof to IP69K - No Audio (PAL", currentStock: "8962", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "2808A", modelNo: "VBV-710C", description: "Select Camera, Heated Shutter & Audio (PAL)", currentStock: "0", replacement: "8034", replacementAvailable: "YES" },
  { productCode: "2808B", modelNo: "VBV-710C", description: "Select Camera, Heated Shutter & Audio (PAL)", currentStock: "16", replacement: "8034", replacementAvailable: "YES" },
  { productCode: "2808C", modelNo: "VBV-710C", description: "Select Camera, Heated Shutter & Audio (PAL)", currentStock: "1831", replacement: "8034", replacementAvailable: "YES" },
  { productCode: "2841A", modelNo: "VBV-711C", description: "Select Camera, Heated Shutter & Audio (NTSC)", currentStock: "1", replacement: "8039", replacementAvailable: "YES" },
  { productCode: "2841B", modelNo: "VBV-711C", description: "Select Camera, Heated Shutter & Audio (NTSC)", currentStock: "6", replacement: "8039", replacementAvailable: "YES" },
  { productCode: "2841C", modelNo: "VBV-711C", description: "Select Camera, Heated Shutter & Audio (NTSC)", currentStock: "127", replacement: "8039", replacementAvailable: "YES" },
  { productCode: "2842B", modelNo: "VBV-791C", description: "Select Camera, W/Proof to IP69K - No Audio (NTSC)", currentStock: "0", replacement: "", replacementAvailable: "YES" },
  { productCode: "2842C", modelNo: "VBV-791C", description: "Select Camera, W/Proof to IP69K - No Audio (NTSC)", currentStock: "36", replacement: "", replacementAvailable: "YES" },
  { productCode: "2842D", modelNo: "VBV-791C", description: "Select Camera, Waterproof to IP69K - No Audio (NTS", currentStock: "624", replacement: "", replacementAvailable: "YES" },
  { productCode: "2843C", modelNo: "VBV-481C", description: "Select Camera, Cylinder Camera (NTSC)", currentStock: "521", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "2871C", modelNo: "BE-890C", description: "Elite Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "0", replacement: "1623E", replacementAvailable: "YES" },
  { productCode: "2871D", modelNo: "BE-890C", description: "Elite Camera, Waterproof to IP69K - No Audio (PAL)", currentStock: "8", replacement: "1623E", replacementAvailable: "YES" },
  { productCode: "2871E", modelNo: "BE-890C", description: "Elite Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "2679", replacement: "1623E", replacementAvailable: "YES" },
  { productCode: "3383C", modelNo: "VBV-770D-000", description: "CMS Elite, 7\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3397B", modelNo: "VBV-770D-000N", description: "CMS Select, 7 Inch LCD, Single Camera - Large Rigi", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3398A", modelNo: "VBV-770D-010N", description: "VBV-770D-010N", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3708A", modelNo: "VBV-711C (AC)", description: "Select Camera, Heated Shutter & Audio - AC-035", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3809B", modelNo: "VBV-770D-SS1", description: "CMS Select, 7 Inch Monitor, VBV-790C(FG) Camera", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3813D", modelNo: "VBV-770D-SS5", description: "CMS Select, 7 Inch Monitor, VBV-790C(FG) Cameras", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3814D", modelNo: "VBV-770D-SS6", description: "CMS Select, 7 Inch Monitor, VBV-790C(FG) Cameras", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "3901A", modelNo: "VBV-770FM/12-24vdc", description: "Select Monitor, 7\" LCD, 4 Inputs, Audio", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4084A", modelNo: "BE-970WF-692", description: "CMS Elite, 7 Inch W/Proof LCD, Single Camera", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4107C", modelNo: "VBV-770-091", description: "CMS Select, 7 Inch LCD, Single IP69K Camera", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4132B", modelNo: "32-0354-0000", description: "Select Camera, Audio (COBO)", currentStock: "4", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4220A", modelNo: "VBV-750-910", description: "CMS Select, 5 Inch LCD, Select Camera (PAL) (KdB)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4226B", modelNo: "27-0986-0000", description: "CMS Select, 7\" LCD, 1 Cam - Lrg Rigids (PAL)", currentStock: "54", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4287A", modelNo: "VBV-750M", description: "Select Monitor, 5 Inch LCD, 3 Inputs, Audio", currentStock: "478", replacement: "5611A", replacementAvailable: "YES" },
  { productCode: "4288A", modelNo: "VBV-770M", description: "Select Monitor, 7 Inch LCD, 3 Inputs, Audio", currentStock: "1344", replacement: "5611A", replacementAvailable: "YES" },
  { productCode: "4304B", modelNo: "VBV-790C(FG)", description: "Select Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "455", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "4368A", modelNo: "VBV-770M-M", description: "Select Monitor, 7 Inch LCD Monitor ONLY", currentStock: "162", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4474A", modelNo: "VBV-7104FM", description: "Select Monitor, 10.4\" LCD, 4 Inputs, Audio", currentStock: "0", replacement: "6057A", replacementAvailable: "YES" },
  { productCode: "4474B", modelNo: "VBV-7104FM", description: "Select Monitor, 10.4\" LCD, 4 Inputs, Audio", currentStock: "7", replacement: "6057A", replacementAvailable: "YES" },
  { productCode: "4692A", modelNo: "VBV-770-000", description: "CMS Select, 7\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4692B", modelNo: "VBV-770-000", description: "CMS Select, 7\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "6", replacement: "AHD version: 8144", replacementAvailable: "YES" },
  { productCode: "4692C", modelNo: "VBV-770-000", description: "CMS Select, 7\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "1110", replacement: "AHD version: 8144", replacementAvailable: "YES" },
  { productCode: "4693B", modelNo: "VBV-770-000N", description: "CMS Select, 7 Inch LCD, Single Camera", currentStock: "0", replacement: "6123", replacementAvailable: "YES" },
  { productCode: "4693C", modelNo: "VBV-770-000N", description: "CMS Select, 7 Inch LCD, Single Camera", currentStock: "64", replacement: "6123", replacementAvailable: "YES" },
  { productCode: "4694B", modelNo: "VBV-770-010N", description: "CMS Select, 7 Inch LCD, Single Camera", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4695B", modelNo: "VBV-770-100", description: "CMS Select, 7\" LCD, 1 Shut Cam - Lrg Rigids (PAL)", currentStock: "69", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4695C", modelNo: "VBV-770-100", description: "CMS Select, 7\" LCD, 1 Shut Cam - Lrg Rigids (PAL)", currentStock: "459", replacement: "AHD version: 7246", replacementAvailable: "YES" },
  { productCode: "4697A", modelNo: "VBV-770M-S", description: "Select Monitor, 7\" LCD, 3 Inputs, Audio", currentStock: "255", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4705B", modelNo: "VBV-750-000", description: "CMS Select, 5\" LCD, Single Cam - Lrg Rigids (PAL)", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4705C", modelNo: "VBV-750-000", description: "CMS Select, 5\" LCD,Single Camera - Lrg Rigid (PAL)", currentStock: "43", replacement: "AHD version: 8144", replacementAvailable: "YES" },
  { productCode: "4706B", modelNo: "VBV-750-000N", description: "CMS Select, 5 Inch LCD, Single Camera - Large Rigi", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4706C", modelNo: "VBV-750-000N", description: "CMS Select, 5 Inch LCD, Single Camera - Large Rigi", currentStock: "35", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4707A", modelNo: "VBV-750-010N", description: "CMS Select, 5 Inch LCD, Single Camera - Small Rigi", currentStock: "25", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4707B", modelNo: "VBV-750-010N", description: "CMS Select, 5 Inch LCD, Single Camera - Small Rigi", currentStock: "25", replacement: "", replacementAvailable: "YES" },
  { productCode: "4708B", modelNo: "VBV-750-100", description: "CMS Select, 5\" LCD, 1 Shut Cam - Lrg Rigids (PAL)", currentStock: "9", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4708C", modelNo: "VBV-750-100", description: "CMS Select, 5 Inch LCD, Single Shutter Camera", currentStock: "62", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4710A", modelNo: "VBV-750M-S", description: "Select Monitor, 5\" LCD, 3 Inputs, Audio", currentStock: "121", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4765B", modelNo: "VBV-650-000", description: "CMS Essential, 5\" LCD, Single Cam - Lrg Rigids", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4765C", modelNo: "VBV-650-000", description: "CMS Essential, 5\" LCD, Single Cam - Lrg Rigids", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4767B", modelNo: "VBV-770-001", description: "CMS Select, 7 Inch LCD, Single Camera - Articulate", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4770A", modelNo: "VBV-770-100N", description: "CMS Select, 7 Inch LCD, Single Shutter Camera", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4772A", modelNo: "VBV-770-101", description: "CMS Select, 7 Inch LCD, Single Shutter Camera", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4773B", modelNo: "VBV-770-002", description: "CMS Select, 7 Inch LCD, Twin Camera - Large Rigids", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4774B", modelNo: "VBV-770-004", description: "CMS Select, 7\" LCD, 2 x Cams", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4776A", modelNo: "VBV-750-300", description: "CMS Select, 5 Inch LCD, Flush-Mount Camera - Large", currentStock: "5", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4777B", modelNo: "VBV-770-300", description: "CMS Select, 7 Inch LCD, Flush-Mount Camera - Large", currentStock: "11", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4780A", modelNo: "VBV-750-310", description: "CMS Select, 5\" LCD, F/Mount Cam- Sml Rigids (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4781B", modelNo: "VBV-770-310", description: "CMS Select, 7\" LCD, F/mount Cam - Sml Rigids (PAL)", currentStock: "30", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4782A", modelNo: "VBV-750-311", description: "CMS Select, 5 Inch LCD, Flush-Mount Camera - Small", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4789B", modelNo: "VBV-750-001", description: "CMS Select, 5 Inch LCD, Single Camera - Articulate", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4790B", modelNo: "VBV-750-004", description: "CMS Select, 5 Inch LCD, Twin Cameras - Truck & Dra", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4791B", modelNo: "VBV-750-010", description: "CMS Select, 5 Inch LCD, Single Camera - Small Rigi", currentStock: "2", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4798B", modelNo: "VBV-750-002", description: "CMS Select, 5 Inch LCD, Twin Cameras - Articulated", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4804C", modelNo: "SE-770-100", description: "Backeye®360 BN-360 Kit, 7\" Monitor - Lrg Rigids", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4843B", modelNo: "VBV-770-001DW", description: "7\" LCD, Single Cam & Wireless Kit", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4850B", modelNo: "VBV-770-090", description: "CMS Select, 7\" LCD, Single System (KdB)", currentStock: "11", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4850C", modelNo: "VBV-770-090", description: "CMS Select, 7\" LCD, Single System (KdB)", currentStock: "6", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4855B", modelNo: "VBV-770D-SS10", description: "CMS Select, 7 Inch Monitor, VBV-790C(FG) Cameras", currentStock: "5", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4856B", modelNo: "VBV-770D-SS11", description: "CMS Select, 7 Inch Monitor, VBV-790C(FG) Cameras", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4858A", modelNo: "MDR-504A(MCPH)", description: "CMS & MDR Kit (MCPHERSON)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4909A", modelNo: "MD-50", description: "Elite Camera, Mini Dome Camera (PAL)", currentStock: "37", replacement: "5737", replacementAvailable: "YES" },
  { productCode: "4910A", modelNo: "DMC-1025", description: "Elite Camera, Mini Camera (Internal Use) (PAL)", currentStock: "11", replacement: "5719 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "4919B", modelNo: "VBV-750-2B", description: "CMS Select, 5 Inch LCD, 2 x VBV-700C Cameras (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "4982A", modelNo: "VBV-770FM", description: "Select Monitor, 7\" LCD, 4 Inputs, Audio", currentStock: "10", replacement: "7204", replacementAvailable: "YES" },
  { productCode: "5052B", modelNo: "VBV-750-090", description: "CMS Select, 5\" LCD, Select Camera (PAL) (KdB)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5075A", modelNo: "VBV-700C-002", description: "Select Camera, Audio + Cable + Cable Adapter (DAF)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5155A", modelNo: "VBV-770F-692", description: "CMS Select, 7 Inch LCD, Quad System (KdB)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "5163A", modelNo: "DMC-1021", description: "Elite Camera, Mini Camera (Internal Use) (NTSC)", currentStock: "12", replacement: "5721 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "5215A", modelNo: "VBV-320C", description: "Select Camera, F/mount Eyeball (Normal) (PAL)", currentStock: "2238", replacement: "7145", replacementAvailable: "YES" },
  { productCode: "5217A", modelNo: "VBV-321C", description: "Select Camera, F/mount Eyeball (Normal) (NTSC)", currentStock: "249", replacement: "7146", replacementAvailable: "YES" },
  { productCode: "5493A", modelNo: "VBV-790C(CO)", description: "VBV-790C Camera with Conduit", currentStock: "1390", replacement: "New item will be created by end of October 2025", replacementAvailable: "YES" },
  { productCode: "A1380", modelNo: "VBV-L420", description: "Select Camera Ext Cable - 20m", currentStock: "2407", replacement: "5513", replacementAvailable: "YES" },
  { productCode: "A1382", modelNo: "VBV-750-200", description: "VBV-750-200", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A1386", modelNo: "VBV-L410", description: "Select Camera Ext Cable - 10m", currentStock: "4652", replacement: "5516", replacementAvailable: "YES" },
  { productCode: "A1499", modelNo: "VBV-L405", description: "Select Camera Ext Cable - 5m", currentStock: "5327", replacement: "5519", replacementAvailable: "YES" },
  { productCode: "A1554", modelNo: "VBV-L4025", description: "Select Camera Ext Cable - 2.5m", currentStock: "6309,5", replacement: "5522", replacementAvailable: "YES" },
  { productCode: "A1836", modelNo: "VBV-750-201", description: "Select Camera System For Rigid Vehicles", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A1927", modelNo: "BE-820C", description: "Elite Camera, Mini Camera (Mirror Image) (PAL)", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A1927A", modelNo: "BE-820C", description: "Elite Camera, Mini Camera (Mirror Image) (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A2108", modelNo: "VBV-L430", description: "Select Camera Ext Cable - 30m", currentStock: "296", replacement: "5511", replacementAvailable: "YES" },
  { productCode: "A2199A", modelNo: "VBV-485C", description: "Select Camera, Cylinder Camera (PAL)", currentStock: "2", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A2724A", modelNo: "VBV-790C", description: "Select Camera, W/Proof to IP69K - No Audio (PAL)", currentStock: "1", replacement: "5466A", replacementAvailable: "YES" },
  { productCode: "A2839B", modelNo: "BE-870F-300", description: "CMS Elite, 7\" LCD, Single Camera (PAL)", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A2842A", modelNo: "VBV-791C", description: "Select Camera, Waterproof to IP69K - No Audio (NTS", currentStock: "0", replacement: "", replacementAvailable: "YES" },
  { productCode: "A3106", modelNo: "VBV-L412", description: "Select Camera Ext Cable - 12m", currentStock: "152", replacement: "5515", replacementAvailable: "YES" },
  { productCode: "A3663", modelNo: "VBV-L510", description: "Select Camera Cable, 5-pin for VBV-710C Camera 10m", currentStock: "662", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A3664", modelNo: "VBV-L520", description: "Select Camera Cable, 5-pin for VBV-710C Camera 20m", currentStock: "866", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "A3883", modelNo: "BE-890C(CNH)", description: "Elite Camera, Waterproof to IP69K - No Audio (PAL)", currentStock: "7", replacement: "1623E", replacementAvailable: "YES" },
  { productCode: "C1529A", modelNo: "DMC-1025", description: "Elite Camera, Mini Camera + BE-L100 Connector", currentStock: "3", replacement: "5719 - however, this has been placed on discontinuation by the supplier. Replacement for this TBC", replacementAvailable: "YES" },
  { productCode: "F2151", modelNo: "BE-822C", description: "Elite Camera, Mini Camera (Normal Image) (PAL)", currentStock: "3", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "F2151A", modelNo: "BE-822C", description: "Elite Camera, Mini Camera (Normal Image) (PAL)", currentStock: "0", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "F3150", modelNo: "VBV-L415", description: "Select Camera Ext Cable - 15m", currentStock: "5166", replacement: "5514", replacementAvailable: "YES" },
  { productCode: "G2540", modelNo: "VSK-50E", description: "Coiled Cable Kit, Select, Twin Camera - Drawbar Tr", currentStock: "30", replacement: "No replacement", replacementAvailable: "NO" },
  { productCode: "G2542", modelNo: "VSK-30E-T", description: "Coiled Cable Kit, Select, Trailer Only Section of", currentStock: "1", replacement: "No replacement", replacementAvailable: "NO" }
]