import { AnalysisResult, Product } from "../types";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import JSZip from "jszip";
import * as XLSX from "xlsx";

// --- THEME COLORS ---
const COLOR_PRIMARY: [number, number, number] = [249, 115, 22]; // Orange-500
const COLOR_SECONDARY: [number, number, number] = [31, 41, 55]; // Gray-800
const COLOR_ACCENT: [number, number, number] = [14, 165, 233]; // Sky-500
const COLOR_TEXT: [number, number, number] = [50, 50, 50];
const COLOR_PRICE_BG: [number, number, number] = [220, 252, 231]; // Green-100
const COLOR_PRICE_TEXT: [number, number, number] = [21, 128, 61]; // Green-700
const COLOR_WARNING: [number, number, number] = [220, 38, 38]; // Red-600

// --- HELPERS ---

const trToAscii = (str: string | null | undefined) => {
  if (!str) return "";
  return str
    .replace(/ğ/g, 'g').replace(/Ğ/g, 'G')
    .replace(/ü/g, 'u').replace(/Ü/g, 'U')
    .replace(/ş/g, 's').replace(/Ş/g, 'S')
    .replace(/ı/g, 'i').replace(/İ/g, 'I')
    .replace(/ö/g, 'o').replace(/Ö/g, 'O')
    .replace(/ç/g, 'c').replace(/Ç/g, 'C')
    .replace(/â/g, 'a').replace(/Â/g, 'A')
    .replace(/î/g, 'i').replace(/Î/g, 'I');
};

const cleanHtmlText = (html: string) => {
    if (!html) return "";
    let text = html
       .replace(/<br\s*\/?>/gi, '\n')
       .replace(/<\/p>/gi, '\n')
       .replace(/<\/h[1-6]>/gi, '\n\n')
       .replace(/<\/li>/gi, '\n')
       .replace(/<[^>]+>/g, '') // Strip remaining tags
       .replace(/&nbsp;/g, ' ');
    return trToAscii(text).trim();
};

// --- CORE PDF GENERATOR (MAIN REPORT) ---

const generatePDFBlob = (result: AnalysisResult): Blob => {
     const doc = new jsPDF();
     const width = doc.internal.pageSize.width;
     const height = doc.internal.pageSize.height;
     const margin = 14;

     // 1. COVER PAGE
     // ----------------------------------------------------------------
     
     // Decorative Side Bar
     doc.setFillColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
     doc.rect(0, 0, 10, height, 'F');

     // Logo / Brand
     doc.setFontSize(30);
     doc.setFont('helvetica', 'bold');
     doc.setTextColor(COLOR_SECONDARY[0], COLOR_SECONDARY[1], COLOR_SECONDARY[2]);
     doc.text(trToAscii("T-SA"), 25, 60);
     doc.text(trToAscii("TURHAN SARTNAME ANALIZI"), 25, 75);

     doc.setDrawColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
     doc.setLineWidth(1);
     doc.line(25, 85, 100, 85);

     // Details
     doc.setFontSize(12);
     doc.setFont('helvetica', 'normal');
     doc.setTextColor(80, 80, 80);
     
     doc.text(trToAscii("DOSYA ADI:"), 25, 110);
     doc.setFont('helvetica', 'bold');
     doc.text(trToAscii(result.fileName), 60, 110);
     
     doc.setFont('helvetica', 'normal');
     doc.text(trToAscii("OLUSTURULMA TARIHI:"), 25, 120);
     doc.setFont('helvetica', 'bold');
     doc.text(new Date().toLocaleDateString('tr-TR'), 75, 120);

     doc.setFont('helvetica', 'normal');
     doc.text(trToAscii("URUN SAYISI:"), 25, 130);
     doc.setFont('helvetica', 'bold');
     doc.text(String(result.products.length), 60, 130);

     // Footer on Cover
     doc.setFontSize(10);
     doc.setFont('helvetica', 'italic');
     doc.setTextColor(150);
     doc.text(trToAscii("Generated by T-SA - Made by G.T"), 25, height - 20);

     // 2. EXECUTIVE SUMMARY & GENERAL PROVISIONS
     // ----------------------------------------------------------------
     doc.addPage();
     
     let currentY = 20;

     doc.setFontSize(16);
     doc.setFont('helvetica', 'bold');
     doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
     doc.text(trToAscii("1. YONETICI OZETI"), margin, currentY);
     currentY += 10;

     doc.setFontSize(10);
     doc.setFont('helvetica', 'normal');
     doc.setTextColor(COLOR_TEXT[0], COLOR_TEXT[1], COLOR_TEXT[2]);
     
     const summaryText = trToAscii(result.summary);
     const summaryLines = doc.splitTextToSize(summaryText, width - (margin * 2));
     doc.text(summaryLines, margin, currentY);
     currentY += (summaryLines.length * 5) + 15;

     // General Provisions Table
     if (result.generalProvisions) {
         // Check page space
         if (currentY > height - 60) {
             doc.addPage();
             currentY = 20;
         }

         doc.setFontSize(16);
         doc.setFont('helvetica', 'bold');
         doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
         doc.text(trToAscii("2. GENEL HUKUMLER"), margin, currentY);
         currentY += 5;

         const gp = result.generalProvisions;
         const gpData = [
             ['Garanti', trToAscii(gp.warrantyConditions)],
             ['Bakim', trToAscii(gp.maintenanceRequirements)],
             ['Kurulum', trToAscii(gp.installationAndCommissioning)],
             ['Egitim', trToAscii(gp.trainingRequirements)],
             ['Sertifikalar', trToAscii((gp.certificationRequirements || []).join(", "))],
             ['Diger', trToAscii(gp.otherTerms || '-')]
         ];

         autoTable(doc, {
             startY: currentY,
             head: [['Konu', 'Aciklama']],
             body: gpData,
             theme: 'grid',
             headStyles: { fillColor: COLOR_SECONDARY, textColor: 255, fontStyle: 'bold' },
             columnStyles: {
                 0: { cellWidth: 40, fontStyle: 'bold', textColor: COLOR_SECONDARY },
                 1: { cellWidth: 'auto' }
             },
             margin: { left: margin, right: margin }
         });
         
         // @ts-ignore
         currentY = doc.lastAutoTable.finalY + 20;
     }

     // 3. PRODUCT DETAILS
     // ----------------------------------------------------------------
     
     result.products.forEach((p, index) => {
         doc.addPage();
         let y = 20;

         // Product Header Box
         doc.setFillColor(240, 240, 240);
         doc.rect(margin, y - 5, width - (margin * 2), 25, 'F');
         
         doc.setFontSize(14);
         doc.setFont('helvetica', 'bold');
         doc.setTextColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
         doc.text(trToAscii(`${index + 1}. ${p.name}`), margin + 5, y + 5);
         
         doc.setFontSize(10);
         doc.setFont('helvetica', 'normal');
         doc.setTextColor(60, 60, 60);
         doc.text(trToAscii(`Kategori: ${p.category}  |  Miktar: ${p.quantity || '1'}  |  Parca No: ${p.partNumber || '-'}`), margin + 5, y + 14);
         
         y += 30;

         // Specifications Table
         doc.setFontSize(12);
         doc.setFont('helvetica', 'bold');
         doc.setTextColor(COLOR_SECONDARY[0], COLOR_SECONDARY[1], COLOR_SECONDARY[2]);
         doc.text(trToAscii("Teknik Gereksinimler"), margin, y);
         y += 5;

         const specBody = p.specifications.map(s => [
             trToAscii(s.group || 'Genel'),
             trToAscii(s.parameter),
             trToAscii(s.value),
             trToAscii(s.unit || ''),
             trToAscii(s.sourceReference || '')
         ]);

         autoTable(doc, {
             startY: y,
             head: [['Grup', 'Parametre', 'Deger', 'Birim', 'Ref']],
             body: specBody,
             theme: 'striped',
             headStyles: { fillColor: [55, 65, 81], textColor: 255, fontSize: 9 },
             bodyStyles: { fontSize: 9, textColor: 50 },
             columnStyles: {
                 0: { cellWidth: 25, fontStyle: 'bold', textColor: [100, 100, 100] },
                 1: { cellWidth: 50, fontStyle: 'bold' },
                 2: { cellWidth: 'auto' },
                 3: { cellWidth: 20 },
                 4: { cellWidth: 25, fontStyle: 'italic', textColor: [100, 100, 100] }
             },
             margin: { left: margin, right: margin },
             // Highlight essential rows
             didParseCell: (data: any) => {
                 const rowSpec = p.specifications[data.row.index];
                 if (rowSpec && rowSpec.criticality === 'Essential' && data.section === 'body') {
                     data.cell.styles.fontStyle = 'bold';
                     if(data.column.index === 1) data.cell.styles.textColor = [220, 38, 38]; // Red for param name
                 }
             }
         });

         // @ts-ignore
         y = doc.lastAutoTable.finalY + 15;
     });

     // 4. ADD FOOTERS & PAGE NUMBERS
     // ----------------------------------------------------------------
     const pageCount = doc.getNumberOfPages();
     for (let i = 1; i <= pageCount; i++) {
         doc.setPage(i);
         // Skip Cover
         if (i === 1) continue;

         doc.setFontSize(8);
         doc.setTextColor(150);
         
         // Footer Line
         doc.setDrawColor(220);
         doc.line(margin, height - 15, width - margin, height - 15);

         // Left: Confidential
         doc.text("GIZLI / TICARI SIR - T-SA Tarafindan Uretilmistir", margin, height - 10);
         
         // Right: Page Number
         doc.text(`Sayfa ${i} / ${pageCount}`, width - margin - 20, height - 10);
     }

     return doc.output('blob');
};

// --- MARKET ANALYSIS SPECIFIC PDF GENERATOR ---

const generateMarketAnalysisPDFBlob = (result: AnalysisResult): Blob | null => {
    // Only proceed if there is market analysis
    const analyzedProducts = result.products.filter(p => p.marketAnalysis && p.marketAnalysis.content);
    if (analyzedProducts.length === 0) return null;

    const doc = new jsPDF();
    const width = doc.internal.pageSize.width;
    const height = doc.internal.pageSize.height;
    const margin = 14;

    // --- COVER ---
    doc.setFillColor(30, 41, 59); // Slate-800
    doc.rect(0, 0, width, height, 'F');
    
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text(trToAscii("PIYASA ARASTIRMA"), width/2, height/2 - 10, { align: 'center' });
    doc.text(trToAscii("& TEDARIKCI RAPORU"), width/2, height/2 + 5, { align: 'center' });
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text(trToAscii(result.fileName), width/2, height/2 + 25, { align: 'center' });

    // --- CONTENT ---
    
    analyzedProducts.forEach((p, index) => {
        doc.addPage();
        let y = 20;

        // Product Header
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(COLOR_ACCENT[0], COLOR_ACCENT[1], COLOR_ACCENT[2]);
        doc.text(trToAscii(`${index + 1}. ${p.name}`), margin, y);
        y += 8;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100);
        doc.text(trToAscii(`Kategori: ${p.category} - Model/Parca No: ${p.partNumber || 'Belirtilmemis'}`), margin, y);
        
        doc.setDrawColor(200);
        doc.line(margin, y + 4, width - margin, y + 4);
        y += 15;

        // PARSING HTML CONTENT
        const container = document.createElement('div');
        container.innerHTML = p.marketAnalysis!.content;

        // Iterate through top-level elements
        Array.from(container.children).forEach((child) => {
            const tagName = child.tagName.toLowerCase();
            const textContent = trToAscii(child.textContent || "");
            
            // Check page break needed before adding element block
            if (y > height - 30) { doc.addPage(); y = 20; }

            if (tagName === 'h3') {
                // Product Title (e.g., Brand - Model)
                y += 5;
                if (y > height - 20) { doc.addPage(); y = 20; }

                doc.setFontSize(12);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(COLOR_SECONDARY[0], COLOR_SECONDARY[1], COLOR_SECONDARY[2]);
                
                // Add a small decorative bar
                doc.setFillColor(COLOR_PRIMARY[0], COLOR_PRIMARY[1], COLOR_PRIMARY[2]);
                doc.rect(margin, y - 4, 4, 4, 'F');
                
                doc.text(textContent, margin + 8, y);
                y += 8;

            } else if (child.className && child.className.includes('price-tag')) {
                // Price Tag Box
                doc.setFontSize(10);
                doc.setFont('helvetica', 'bold');
                doc.setTextColor(COLOR_PRICE_TEXT[0], COLOR_PRICE_TEXT[1], COLOR_PRICE_TEXT[2]);
                
                const dims = doc.getTextDimensions(textContent);
                doc.setFillColor(COLOR_PRICE_BG[0], COLOR_PRICE_BG[1], COLOR_PRICE_BG[2]);
                doc.setDrawColor(COLOR_PRICE_TEXT[0], COLOR_PRICE_TEXT[1], COLOR_PRICE_TEXT[2]);
                
                doc.roundedRect(margin, y - 4, dims.w + 10, dims.h + 6, 1, 1, 'FD');
                doc.text(textContent, margin + 5, y + 1);
                y += 12;

            } else if (tagName === 'table') {
                // Compliance Table
                const headers: string[] = [];
                const body: string[][] = [];

                // Parse Table Header
                const ths = child.querySelectorAll('th');
                ths.forEach(th => headers.push(trToAscii(th.textContent || '')));

                // Parse Table Body
                const trs = child.querySelectorAll('tbody tr');
                if (trs.length === 0) {
                     // Fallback if no tbody
                     const allTrs = child.querySelectorAll('tr');
                     allTrs.forEach((tr, i) => {
                         if (i === 0 && ths.length > 0) return; // skip header if already parsed
                         const tds = tr.querySelectorAll('td');
                         const row: string[] = [];
                         tds.forEach(td => row.push(trToAscii(td.textContent || '')));
                         if(row.length > 0) body.push(row);
                     });
                } else {
                     trs.forEach(tr => {
                         const tds = tr.querySelectorAll('td');
                         const row: string[] = [];
                         tds.forEach(td => row.push(trToAscii(td.textContent || '')));
                         body.push(row);
                     });
                }

                autoTable(doc, {
                    startY: y,
                    head: [headers.length ? headers : ['Ozellik', 'Sartname', 'Urun', 'Durum']],
                    body: body,
                    theme: 'striped',
                    headStyles: { fillColor: COLOR_SECONDARY, textColor: 255, fontSize: 8 },
                    bodyStyles: { fontSize: 8, textColor: 50 },
                    margin: { left: margin, right: margin },
                    styles: { overflow: 'linebreak' },
                    columnStyles: {
                        0: { cellWidth: 20 },
                        3: { cellWidth: 20, fontStyle: 'bold' } // Status column
                    }
                });
                // @ts-ignore
                y = doc.lastAutoTable.finalY + 10;

            } else if (tagName === 'ul') {
                // List Handling
                doc.setFontSize(9);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(60);
                
                const lis = child.querySelectorAll('li');
                lis.forEach(li => {
                    const liText = "• " + trToAscii(li.textContent || "");
                    const lines = doc.splitTextToSize(liText, width - (margin * 2) - 5);
                    
                    // Check Pagination for each list item
                    if (y + (lines.length * 4) > height - margin) {
                        doc.addPage();
                        y = margin;
                    }

                    doc.text(lines, margin + 5, y);
                    y += (lines.length * 4) + 2;
                });
                y += 2;

            } else {
                // Regular Paragraphs
                doc.setFontSize(9);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(60);

                // Check for tech-notes (red text)
                if (child.innerHTML.includes('tech-note')) {
                     doc.setTextColor(COLOR_WARNING[0], COLOR_WARNING[1], COLOR_WARNING[2]);
                }

                const lines = doc.splitTextToSize(textContent, width - (margin * 2));
                
                // Line-by-line printing to handle page breaks within a paragraph
                lines.forEach((line: string) => {
                    if (y > height - margin) {
                        doc.addPage();
                        y = margin;
                    }
                    doc.text(line, margin, y);
                    y += 4;
                });
                y += 2; // Spacing after paragraph
            }
        });

        // Add Sources Footnote if any
        if (p.marketAnalysis!.sources.length > 0) {
            y += 5;
            if (y > height - 40) { doc.addPage(); y = 20; }
            doc.setFontSize(8);
            doc.setFont('helvetica', 'italic');
            doc.setTextColor(150);
            doc.text("Kaynaklar:", margin, y);
            y+=4;
            p.marketAnalysis!.sources.forEach(src => {
                if (y > height - 15) { doc.addPage(); y = 20; }
                doc.text(trToAscii(`- ${src.title} (${src.uri})`), margin, y);
                y+=4;
            });
        }
    });

    // Add footer numbers
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        if (i === 1) continue;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Sayfa ${i} / ${pageCount}`, width - margin - 20, height - 10);
    }

    return doc.output('blob');
};

const generateExcelBlob = (result: AnalysisResult): Blob => {
    const wb = XLSX.utils.book_new();

    // ---------------------------------------------------------
    // SHEET 1: ÜRÜN LİSTESİ VE PİYASA ANALİZİ (ÖZET)
    // ---------------------------------------------------------
    const productHeaders = ["Kategori", "Ürün Adı", "Parça No", "Miktar", "Açıklama", "Piyasa Analizi", "Kaynaklar"];
    const productRows = [productHeaders];

    result.products.forEach(p => {
        const hasAnalysis = !!p.marketAnalysis;
        // Clean HTML to text, truncate to Excel limit just in case
        const marketNotes = hasAnalysis ? cleanHtmlText(p.marketAnalysis!.content).substring(0, 32000) : "";
        const sources = hasAnalysis ? p.marketAnalysis!.sources.map(s => s.uri).join(", ") : "";

        productRows.push([
            p.category,
            p.name,
            p.partNumber || '',
            p.quantity || '',
            p.description,
            marketNotes,
            sources
        ]);
    });

    const wsProducts = XLSX.utils.aoa_to_sheet(productRows);
    wsProducts['!cols'] = [{wch: 15}, {wch: 30}, {wch: 15}, {wch: 10}, {wch: 40}, {wch: 50}, {wch: 30}];
    XLSX.utils.book_append_sheet(wb, wsProducts, "Ürün Listesi");

    // ---------------------------------------------------------
    // SHEET 2: TÜM TEKNİK ÖZELLİKLER (DETAY)
    // ---------------------------------------------------------
    const specHeaders = ["Kategori", "Ürün Adı", "Grup", "Parametre", "Değer", "Birim", "Koşul", "Önem", "Referans"];
    const specRows = [specHeaders];

    result.products.forEach(p => {
        p.specifications.forEach(spec => {
            specRows.push([
                p.category,
                p.name,
                spec.group || '',
                spec.parameter,
                spec.value,
                spec.unit || '',
                spec.condition || '',
                spec.criticality || '',
                spec.sourceReference || ''
            ]);
        });
    });

    const wsSpecs = XLSX.utils.aoa_to_sheet(specRows);
    wsSpecs['!cols'] = [{wch: 15}, {wch: 25}, {wch: 15}, {wch: 25}, {wch: 25}, {wch: 10}, {wch: 15}, {wch: 10}, {wch: 15}];
    XLSX.utils.book_append_sheet(wb, wsSpecs, "Teknik Detaylar");

    // ---------------------------------------------------------
    // SHEET 3: GENEL ŞARTLAR
    // ---------------------------------------------------------
    if (result.generalProvisions) {
        const gp = result.generalProvisions;
        const gpData = [
            ["Konu", "Açıklama"],
            ["Garanti", gp.warrantyConditions],
            ["Bakım", gp.maintenanceRequirements],
            ["Kurulum", gp.installationAndCommissioning],
            ["Eğitim", gp.trainingRequirements],
            ["Teslimat", gp.deliveryAndLogistics],
            ["Sertifikalar", (gp.certificationRequirements || []).join(", ")],
            ["Diğer", gp.otherTerms]
        ];
        const wsGp = XLSX.utils.aoa_to_sheet(gpData);
        wsGp['!cols'] = [{ wch: 20 }, { wch: 80 }];
        XLSX.utils.book_append_sheet(wb, wsGp, "Genel Şartlar");
    }

    // Write to buffer
    const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    return new Blob([wbout], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
};

export const generateReportZip = async (result: AnalysisResult) => {
    const zip = new JSZip();
    
    // 1. Main PDF Report
    const pdfBlob = generatePDFBlob(result);
    zip.file("Genel_Rapor.pdf", pdfBlob);

    // 2. Excel Report
    const excelBlob = generateExcelBlob(result);
    zip.file("Analiz_Tablosu.xlsx", excelBlob);

    // 3. Project Source JSON
    const jsonStr = JSON.stringify(result, null, 2);
    zip.file("proje.sart", jsonStr);

    // 4. Market Analysis PDF Report (Professional)
    const marketPdfBlob = generateMarketAnalysisPDFBlob(result);
    if (marketPdfBlob) {
        zip.file("Tedarikci_Piyasa_Raporu.pdf", marketPdfBlob);
    }

    // 5. Raw HTML (Backup - Optional, keep for debugging or raw text)
    // We keep this just in case they want the raw html text still
    const marketContent = result.products
        .filter(p => p.marketAnalysis)
        .map(p => `<h1>${p.name}</h1>\n${p.marketAnalysis?.content}`)
        .join("\n<hr/>\n");
        
    if (marketContent) {
        const htmlReport = `
        <html>
        <head>
          <meta charset="utf-8">
          <style>
             body { font-family: sans-serif; line-height: 1.6; color: #333; }
             h1 { border-bottom: 2px solid #ff6b00; padding-bottom: 5px; color: #333; }
             .price-tag { background: #e6fffa; color: #009068; padding: 5px 10px; border-radius: 4px; display: inline-block; font-weight: bold; margin-bottom: 10px; }
             table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
             th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
             th { background-color: #f2f2f2; }
             .tech-note { text-decoration: underline; text-decoration-color: red; text-decoration-thickness: 2px; font-weight: bold; }
          </style>
        </head>
        <body>${marketContent}</body>
        </html>`;
        zip.file("Piyasa_Analizi_Ham.html", htmlReport);
    }

    const content = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(content);
    const link = document.createElement("a");
    link.href = url;
    
    const originalName = result.fileName;
    const lastDotIndex = originalName.lastIndexOf('.');
    const nameWithoutExt = lastDotIndex > 0 ? originalName.substring(0, lastDotIndex) : originalName;
    link.download = `${nameWithoutExt}.zip`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};